package edu.cyc14.essais.pojo;

public enum NavPositionParameterName_E {
    NAV_POSITION_PARAMETER_NAME__LONGITUDE,
    NAV_POSITION_PARAMETER_NAME__LATITUDE,
    NAV_POSITION_PARAMETER_NAME__HEIGHT,
    NAV_POSITION_PARAMETER_NAME__POSITION_ERROR,
    NAV_POSITION_PARAMETER_NAME__HEIGHT_ERROR,
    NAV_POSITION_PARAMETER_NAME__UTC_TIME_OF_DAY,
    NAV_POSITION_PARAMETER_NAME__DATE,
    NAV_POSITION_PARAMETER_NAME__DISTANCE_TRAVELLED
}
