package LDM.navigation;

public enum NavAttitudeParameterName_E {
    NAV_ATTITUDE_PARAMETER_NAME__PITCH,
    NAV_ATTITUDE_PARAMETER_NAME__ROLL,
    NAV_ATTITUDE_PARAMETER_NAME__YAW,
    NAV_ATTITUDE_PARAMETER_NAME__PITCH_RATE,
    NAV_ATTITUDE_PARAMETER_NAME__ROLL_RATE,
    NAV_ATTITUDE_PARAMETER_NAME__YAW_RATE
}
