package LDM.navigation;

public enum NavErrorType_E {
    NAV_ERROR_TYPE__GDOP,
    NAV_ERROR_TYPE__FOM,
    NAV_ERROR_TYPE__CEP,
    NAV_ERROR_TYPE__ERROR_RATING,
    NAV_ERROR_TYPE__NONE_AVAILABLE
}
